#!/bin/bash

add_pkg ()
{
    for p in "$@";
    do
        pacman -Qi $p >/dev/null 2>&1
        if [ $? -eq 1 ]; then
            if [ "$PKG" != "" ]; then
                PKG="$PKG $p"
            else
                PKG="$p"
            fi
        fi
    done
}

install_pkg ()
{
    if [ "$PKG" != "" ]; then
        echo "Installation de: yaourt -S '$PKG'"
        pacman -S $PKG
    fi
}

# Teste si un hostname a été défini
if [ ! -f /etc/hostname ];
    echo "archlinux-host" > /etc/hostname
fi

# Teste si la locale a été défini
grep "^fr_FR.UTF-8" /etc/locale.gen
if [ $? -eq 1 ]; then
    echo "fr_FR.UTF-8" >> /etc/locale.gen
    echo "LANG='fr_FR.UTF-8'" >> /etc/locale.conf 
    locale-gen
fi

# Teste la keymap du pc
if [ ! -f /etc/vconsole.conf ];
    echo "KEYMAP=fr-pc" > /etc/vconsole.conf
fi

# Teste si le localtime a été défini
if [ ! -h /etc/localtime ];
    ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
fi

# Préparation des prérequis
if [ "$(ping -q -c1 8.8.8.8)" && "$(ping -q -c1 www.google.com)" ]; then
    echo "Veuillez vous assurer que vous ayez une connexion internet"
    return
fi

grep archlinuxfr /etc/pacman.conf
if [ $? -eq 1 ]; then
    echo "[archlinuxfr]" >> /etc/pacman.conf
    echo "Server = http://repo.archlinuxfr/$arch" >> /etc/pacman.conf
fi

PKG=""
add_pkg yaourt wget git
add_pkg net-tools
pacman -Syu
install_pkg

# Chargement du dotfiles
if [ ! -d ~/dotfiles ]; then
    cd
    git clone git@github.com:badele/dotfiles.git
else
    git pull
fi
echo "Vous pouvez maintenant utiliser sync_environnement"
