#!/bin/bash

add_pkg ()
{
    for p in "$@";
    do
        pacman -Qi $p >/dev/null 2>&1
        if [ $? -eq 1 ]; then
            if [ "$PKG" != "" ]; then
                PKG="$PKG $p"
            else
                PKG="$p"
            fi
        fi
    done
}

install_pkg ()
{
    if [ "$PKG" != "" ]; then
        echo "Installation de: yaourt -S '$PKG'"
        pacman -S $PKG
    fi
}

if [ "$(ping -q -c1 8.8.8.8)" && "$(ping -q -c1 www.google.com)" ]; then
    echo "Veuillez vous assurer que vous ayez une connexion internet"
    return
fi

grep archlinuxfr /etc/pacman.conf
if [ $? -eq 1 ]; then
    echo "[archlinuxfr]" >> /etc/pacman.conf
    echo "Server = http://repo.archlinuxfr/$arch" >> /etc/pacman.conf
fi


PKG=""
add_pkg yaourt wget git
add_pkg net-tools
pacman -Syu
install_pkg

echo "Vous pouvez maintenant utiliser sync_environnement"
