#!/bin/bash

PKG=""

type mkvirtualenv >/dev/null 2>&1
if [ $? -eq 1 ]; then
	echo "Veuillez creer l'environement avec install_env avec dotfiles/user/tools/install_virtualenv"
	exit
fi

mkvirtualenv --no-site-packages -p python2.7 rstblog
pip install -r ~/dotfiles/rstblog/requirements.txt 

# Récupération des sources
cd ~/projets
git clone git@github.com:badele/rstblog.git
cd ~/projets/rstblog

# Installation
python2 setup.py install
#cp -r rstblog/templates $VIRTUAL_ENV/lib/python2.7/site-packages/rstblog/

