#!/bin/bash

PKG=""
#source ~/dotfiles/system/usr/local/bin/dotfiles.sh
#add_pkg python-pyside python-shiboken
#install_pkg

type mkvirtualenv >/dev/null 2>&1
if [ $? -eq 1 ]; then
	echo "Veuillez creer l'environement avec install_env avec dotfiles/user/tools/install_virtualenv"
	exit
fi

mkvirtualenv --no-site-packages -p python3.3 pyside
pip install -r ~/dotfiles/pyside/requirements.txt 
