#!/bin/bash

if [ ! -d ~/.oh-my-zsh ]; then
    yaourt -S git zsh
    cd ~
    cp .zshrc .zshrc.backup
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
else
    echo "zsh est deja present sur votre systeme"
fi
